config/routes.rb
Rails.application.routes.draw do
  root 'galleries#index'

  resources :galleries, only: [:index, :show]
  # une autre façon d'écrire les 2 routes générées par la ligne précédente
  # get 'galleries', 'galleries#index', as: 'galleries'
  # get 'galleries/:id', 'galleries#show', as: 'gallery'

  namespace :admin do
    resources :galleries
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /admin/galleries
  # GET /admin/galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /admin/galleries/1
  # GET /admin/galleries/1.json
  def show
  end

  # GET /admin/galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /admin/galleries/1/edit
  def edit
  end

  # POST /admin/galleries
  # POST /admin/galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to [:admin, @gallery], notice: 'Gallery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/galleries/1
  # PATCH/PUT /admin/galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to [:admin, @gallery], notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/galleries/1
  # DELETE /admin/galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :published)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for([:admin, @gallery]) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="field">
      <%= f.label :published %><br>
    <%= f.check_box :published %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @gallery] %> |
<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Published</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%= gallery.published %></td>
        <td><%= link_to 'Show', [:admin, gallery] %></td>
        <td><%= link_to 'Edit', edit_admin_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', [:admin, gallery], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>

<p>
  <strong>Published:</strong>
  <%= @gallery.published %>
</p>

<%= link_to 'Edit', edit_admin_gallery_path(@gallery) %> |
<%= link_to 'Back', admin_galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%= gallery.published %></td>
        <td><%= link_to 'Show', gallery %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>

<p>
  <strong>Published:</strong>
  <%= @gallery.published %>
</p>

<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>